import { Navigation } from '@/src/components/Navigator/Navigation';
import styles from './layout.module.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <head>
        <title>BitProduct</title>
      </head>
      <body className={styles.layout}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
